apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    formation.fr/environment: production
    tier: backend
    version: "1.25"
spec:
  containers:
    - name : nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
