apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    tier : backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:alpine
        ports:
        - containerPort: 80
